;==============================================================================

; File: "html#.scm", Time-stamp: <2007-04-04 14:42:33 feeley>

; Copyright (c) 2005-2007 by Marc Feeley, All Rights Reserved.

;==============================================================================

(##namespace ("html#"

              ; procedures
              write-html
              ;tag
              <a>
              <abbr>
              <acronym>
              <address>
              <applet>
              <area>
              <article>
              <aside>
              <audio>
              <b>
              <base>
              <basefont>
              <bdi>
              <bdo>
              <big>
              <blockquote>
              <body>
              <br>
              <button>
              <canvas>
              <caption>
              <center>
              <cite>
              <code>
              <col>
              <colgroup>
              <data>
              <datalist>
              <dd>
              <del>
              <details>
              <dfn>
              <dialog>
              <dir>
              <div>
              <dl>
              <dt>
              <em>
              <embed>
              <fieldset>
              <figcaption>
              <figure>
              <font>
              <footer>
              <form>
              <frame>
              <frameset>
              <h1>
              <h2>
              <h3>
              <h4>
              <h5>
              <h6>
              <head>
              <header>
              <hp1>
              <hp2>
              <hp3>
              <hp4>
              <hp5>
              <hp6>
              <hr>
              <html>
              <i>
              <iframe>
              <img>
              <input>
              <ins>
              <isindex>
              <kbd>
              <label>
              <legend>
              <li>
              <link>
              <listing>
              <main>
              <map>
              <mark>
              <menu>
              <meta>
              <meter>
              <nav>
              <nextid>
              <noframes>
              <noscript>
              <object>
              <ol>
              <optgroup>
              <option>
              <output>
              <p>
              <param>
              <picture>
              <plaintext>
              <pre>
              <progress>
              <q>
              <rp>
              <rt>
              <rtc>
              <ruby>
              <s>
              <samp>
              <script>
              <section>
              <select>
              <small>
              <source>
              <span>
              <strike>
              <strong>
              <style>
              <sub>
              <summary>
              <sup>
              <table>
              <tbody>
              <td>
              <template>
              <textarea>
              <tfoot>
              <th>
              <thead>
              <time>
              <title>
              <tr>
              <track>
              <tt>
              <u>
              <ul>
              <var>
              <video>
              <wbr>
              <xmp>
              make-unprotected))
